# Generated by Django 4.0.6 on 2022-07-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cropyield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cropyield',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('maximum_temperature', models.IntegerField(blank=True, null=True)),
                ('minimum_temperature', models.IntegerField(blank=True, null=True)),
                ('amount_of_precipitation', models.IntegerField(blank=True, null=True)),
                ('weather_station', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'weather',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_max_temp', models.FloatField(blank=True, null=True)),
                ('avg_min_temp', models.FloatField(blank=True, null=True)),
                ('total_accum_precipitation', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('weather_station', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'weather_statistics',
                'managed': False,
            },
        ),
    ]
